### ISSUE TITLE
making make_shell_context

### ISSUE THREAD

**Issue by jjb** [inveniosoftware/flask-cli#9]
Hi,

Thanks for this project!

I'm a flask and python newb (part of the reason I really need a CLI, so I can experiment) and I'm not able to figure out how to make a `make_shell_context` method. Could you give me or point me to an example? I'll put together a PR for the readme so others can benefit. Thanks!

```
$ ~/.local/bin/flask —app=my_app shell
my_app
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/vagrant/.local/lib/python2.7/site-packages/flask_cli/cli.py", line 495, in main
    cli.main(args=args, prog_name=name)
  File "/home/vagrant/.local/lib/python2.7/site-packages/flask_cli/cli.py", line 343, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/flask_cli/cli.py", line 210, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/flask_cli/cli.py", line 458, in shell_command
    ctx.update(app.make_shell_context())
AttributeError: 'Flask' object has no attribute 'make_shell_context'
```

**Comment by lnielsen** [comment]
Following should do the job:

``` python
# app.py
from flask_cli import FlaskCLI
from flask import Flask

app = Flask(__name__)
FlaskCLI(app)

@app.shell_context_processor
def ctx():
    return {'a':'b'}
```

``` console
$ flask -a app.py shell
app
Python 3.5.1 (default, Feb 28 2016, 10:43:54)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
App: app
Instance: /Users/lnielsen/instance
>>> a
'b'
```

The best place for documentation is actually Flask it-self, as we're just making features from the development version of Flask available:
http://flask.pocoo.org/docs/dev/cli/
http://flask.pocoo.org/docs/dev/api/#flask.Flask.shell_context_processor

**Comment by anselal** [comment]
Hi there, 

similar problem. I have this piece of code:

```python
# manager.py
from flask.cli import FlaskGroup
from app import app, db
import click

app = create_app()
cli = FlaskGroup(create_app=create_app)

@app.shell_context_processor
def make_shell_context():
    return dict(app=app, db=db)
```

Then I run:
```sh
$ export FLASK_DEBUG=1
$ python manager.py shell
>>> db
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'db' is not defined
```

What am I missing ?

**Comment by lnielsen** [comment]
Hi,

This question is better asked on Flask itself. You are importing from Flask (``from flask.cli import FlaskGroup``) and not Flask-CLI (``from flask_cli import FlaskGroup``). This extension was a backport of the Click functionality to work with Flask v0.10, but you don't need this extension if you're on Flask v0.11+.

That said, you're mixing [custom scripts](http://flask.pocoo.org/docs/dev/cli/#custom-scripts) with default ``flask`` command.

Perhaps try something like (didn't test it):

```python
# manager.py
from app import app, db
import click

@app.shell_context_processor
def make_shell_context():
    return dict(app=app, db=db)
```

**Comment by anselal** [comment]
Thank you for taking the time to respond.

I managed to figure out that `db` is and other variables set with `shell_context_processor` are available if I call `flask shell` but don't work with `python manager.py shell`.
I guess this is because the decorator is part of `app` and not `cli`. Who knows.

Thank you anyways !!!
